web:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/www/allocine/nginx:/etc/nginx/conf.d
  links:
    - php:php

php:
  image: php:7.1.10-fpm
  volumes:
    - /var/www/allocine:/var/www/html
  links:
    - db:db

db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
     - "8080:80"
  links:
      - db:db