# web:
#   image: tutum/apache-php
#   ports:
#     - "80:80"
#   volumes:
#     - /var/www/mml:/var/www/
#     - /var/www/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
#     - /var/www/docker/sites:/etc/apache2/sites-enabled
#   environment:
#     - ALLOW_OVERRIDE=true
#   links:
#     - db:db
web:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/www/allocine/nginx:/etc/nginx/conf.d
  links:
    - php:php

php:
  image: php:7.1.10-fpm
  volumes:
    - /var/www/allocine:/var/www/html
  links:
    - db:db

db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

